import { AuthError } from '../../../../errors/AuthError';
export declare const handleFailure: (error: AuthError | unknown) => Promise<void>;
